/**
 * OfficerAlerts — Pulls HIGH_RISK and REVIEW screenings from the backend
 * /api/history endpoint and surfaces them as actionable alerts.
 *
 * Alert triggers:
 *  - risk_tier === 'HIGH_RISK'        → Critical threat
 *  - check_watchlist / check_tamper / check_face fields available from ScreeningResult
 *  - risk_tier === 'REVIEW'           → Inspection flag
 */
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  AlertTriangle,
  ShieldAlert,
  ShieldCheck,
  Eye,
  RefreshCw,
  Bell,
} from 'lucide-react';
import { Card } from '../../components/common/Card';
import { Badge } from '../../components/common/Badge';
import { Button } from '../../components/common/Button';
import { EmptyState } from '../../components/common/EmptyState';
import { PageHeader } from '../../components/common/PageHeader';

interface HistoryRecord {
  case_id: string;
  doc_type: string;
  risk_tier: string | null;
  risk_score: number | null;
  extracted_name: string;
  created_at: string;
}

function request(path: string) {
  const token = sessionStorage.getItem('identix_access_token');
  return fetch(path, {
    headers: token ? { Authorization: `Bearer ${token}` } : {},
  });
}

function formatTime(ts: string) {
  if (!ts) return '—';
  return new Date(ts).toLocaleString();
}

export const OfficerAlerts: React.FC = () => {
  const navigate = useNavigate();
  const [records, setRecords] = useState<HistoryRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const load = async (isRefresh = false) => {
    if (isRefresh) setRefreshing(true);
    try {
      const res = await request('/api/history');
      if (res.ok) {
        const all: HistoryRecord[] = await res.json();
        // Only show HIGH_RISK and REVIEW cases as alerts
        const alerts = all.filter(
          (r) => r.risk_tier === 'HIGH_RISK' || r.risk_tier === 'REVIEW',
        );
        // Most recent first
        alerts.sort(
          (a, b) =>
            new Date(b.created_at).getTime() - new Date(a.created_at).getTime(),
        );
        setRecords(alerts);
      }
    } catch {
      // Backend unavailable
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    load();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const highRisk = records.filter((r) => r.risk_tier === 'HIGH_RISK');
  const review = records.filter((r) => r.risk_tier === 'REVIEW');

  const AlertCard: React.FC<{ record: HistoryRecord }> = ({ record }) => {
    const isHigh = record.risk_tier === 'HIGH_RISK';
    return (
      <div
        className={`flex items-center justify-between gap-4 rounded-xl border p-4 transition-colors ${isHigh
            ? 'border-red-200 bg-red-50'
            : 'border-amber-100 bg-amber-50'
          }`}
      >
        <div className="flex items-center gap-3 min-w-0">
          {isHigh ? (
            <ShieldAlert className="w-5 h-5 text-red-600 shrink-0" />
          ) : (
            <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" />
          )}
          <div className="min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="font-mono text-xs font-semibold text-slate-800">
                {record.case_id}
              </span>
              <Badge variant={isHigh ? 'high_risk' : 'review'}>
                {isHigh ? 'HIGH RISK' : 'REVIEW'}
              </Badge>
              {record.risk_score != null && (
                <span className="text-xs text-slate-500">
                  Score: {record.risk_score}
                </span>
              )}
            </div>
            <p className="text-sm text-slate-700 mt-0.5 truncate">
              {record.extracted_name !== 'Unknown'
                ? record.extracted_name
                : 'Name not extracted'}{' '}
              · {record.doc_type || 'Unknown type'}
            </p>
            <p className="text-xs text-slate-400 mt-0.5">{formatTime(record.created_at)}</p>
          </div>
        </div>
        <Button
          variant="outline"
          size="sm"
          icon={<Eye className="w-3.5 h-3.5" />}
          onClick={() => navigate(`/officer/screening/${record.case_id}/results`)}
        >
          Review
        </Button>
      </div>
    );
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Security & Inspection Alerts"
        subtitle="Critical flags generated by Watchlist checks, biometric mismatches, forensic anomalies, and risk engine decisions."
        badge={
          records.length > 0 ? (
            <Badge variant="high_risk" dot>
              {records.length} Active Alert{records.length !== 1 ? 's' : ''}
            </Badge>
          ) : (
            <Badge variant="clear" dot>
              0 Active Threats
            </Badge>
          )
        }
      />

      <div className="flex justify-end">
        <Button
          variant="outline"
          size="sm"
          icon={<RefreshCw className={`w-3.5 h-3.5 ${refreshing ? 'animate-spin' : ''}`} />}
          onClick={() => load(true)}
          disabled={refreshing}
        >
          Refresh
        </Button>
      </div>

      {loading && (
        <Card>
          <p className="text-sm text-slate-500 py-8 text-center">
            Loading alerts from backend…
          </p>
        </Card>
      )}

      {!loading && records.length === 0 && (
        <Card>
          <EmptyState
            icon={<ShieldCheck className="w-6 h-6 text-emerald-600" />}
            title="No Active Inspection Alerts"
            description="There are currently zero unresolved security or document discrepancy alerts. When the verification engine identifies high-risk anomalies, they will appear here."
          />
        </Card>
      )}

      {!loading && highRisk.length > 0 && (
        <Card
          cardTitle={
            <span className="flex items-center gap-2 text-red-700">
              <ShieldAlert className="w-4 h-4" />
              HIGH RISK — Immediate Attention Required ({highRisk.length})
            </span>
          }
        >
          <div className="space-y-3">
            {highRisk.map((r) => (
              <AlertCard key={r.case_id} record={r} />
            ))}
          </div>
        </Card>
      )}

      {!loading && review.length > 0 && (
        <Card
          cardTitle={
            <span className="flex items-center gap-2 text-amber-700">
              <Bell className="w-4 h-4" />
              REVIEW — Manual Inspection Required ({review.length})
            </span>
          }
        >
          <div className="space-y-3">
            {review.map((r) => (
              <AlertCard key={r.case_id} record={r} />
            ))}
          </div>
        </Card>
      )}
    </div>
  );
};
