from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
import io
import database
import security
import logging

logger = logging.getLogger(__name__)

def generate_report(case_id: str) -> bytes:
    record = database.get_record_by_case_id(case_id)
    if not record:
        return b""

    decrypted_name = security.decrypt_field(record["extracted_name_enc"])
    decrypted_doc_number = security.decrypt_field(record["extracted_doc_number_enc"])

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        textColor=colors.HexColor("#0a1628"),
        fontSize=24,
        spaceAfter=12
    )
    subtitle_style = ParagraphStyle(
        'SubtitleStyle',
        parent=styles['Heading2'],
        textColor=colors.HexColor("#0a1628"),
        fontSize=14,
        spaceAfter=20
    )
    
    def get_color_for_status(status):
        if status == "PASSED": return colors.HexColor("#22c55e")
        if status == "FAILED": return colors.HexColor("#ef4444")
        if status == "INCONCLUSIVE": return colors.HexColor("#f59e0b")
        return colors.HexColor("#06b6d4")
        
    def get_color_for_tier(tier):
        if tier == "CLEAR": return colors.HexColor("#22c55e")
        if tier == "HIGH_RISK": return colors.HexColor("#ef4444")
        return colors.HexColor("#f59e0b")

    elements.append(Paragraph("IDentix", title_style))
    elements.append(Paragraph("INVESTIGATION REPORT", subtitle_style))
    
    elements.append(Paragraph(f"<b>Case ID:</b> {record['case_id']}", styles['Normal']))
    elements.append(Paragraph(f"<b>Timestamp:</b> {record['created_at']}", styles['Normal']))
    elements.append(Paragraph(f"<b>Officer ID:</b> {record['officer_id']}", styles['Normal']))
    elements.append(Paragraph(f"<b>Processing Time:</b> {record['processing_time']:.2f}s", styles['Normal']))
    elements.append(Spacer(1, 20))
    
    elements.append(Paragraph("Document Information", styles['Heading3']))
    doc_data = [
        ["Type", record.get("doc_type", "N/A")],
        ["Name", decrypted_name],
        ["DOB", record.get("extracted_dob", "N/A")],
        ["Document #", decrypted_doc_number],
        ["Expiry", record.get("extracted_expiry", "N/A")],
        ["Nationality", record.get("extracted_nationality", "N/A")]
    ]
    t = Table(doc_data, colWidths=[150, 300])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    elements.append(t)
    elements.append(Spacer(1, 20))
    
    elements.append(Paragraph("Verification Checks", styles['Heading3']))
    checks_data = [
        ["Check Name", "Status"],
        ["Document Type", record.get("check_doc_type", "N/A")],
        ["OCR Extraction", record.get("check_ocr", "N/A")],
        ["MRZ Checksum", record.get("check_mrz", "N/A")],
        ["Cross-Field Validation", record.get("check_cross_field", "N/A")],
        ["Document Validity (Expiry)", record.get("check_expiry", "N/A")],
        ["Tamper Detection (ELA)", record.get("check_tamper", "N/A")],
        ["Face Verification", record.get("check_face", "N/A")],
        ["Watchlist Check", record.get("check_watchlist", "N/A")]
    ]
    t2 = Table(checks_data, colWidths=[200, 250])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0a1628")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    elements.append(t2)
    elements.append(Spacer(1, 20))
    
    elements.append(Paragraph("Risk Assessment", styles['Heading3']))
    
    tier = record.get("risk_tier", "UNKNOWN")
    tier_color = get_color_for_tier(tier)
    
    elements.append(Paragraph(f"<b>Risk Tier:</b> {tier}", styles['Normal']))
    elements.append(Paragraph(f"<b>Risk Score:</b> {record.get('risk_score', 'N/A')}", styles['Normal']))
    elements.append(Paragraph(f"<b>Explanation:</b> {record.get('risk_explanation', 'N/A')}", styles['Normal']))
    elements.append(Spacer(1, 20))
    
    elements.append(Paragraph("Audit Trail", styles['Heading3']))
    elements.append(Paragraph(f"<b>Record Hash:</b> <font size=8>{record.get('record_hash', '')}</font>", styles['Normal']))
    elements.append(Paragraph(f"<b>Previous Hash:</b> <font size=8>{record.get('previous_hash', '')}</font>", styles['Normal']))
    elements.append(Spacer(1, 40))
    
    elements.append(Paragraph("<i>This report was generated by IDentix AI Document Verification System. Classification: OFFICIAL - SENSITIVE</i>", styles['Normal']))
    
    doc.build(elements)
    
    return buffer.getvalue()
